/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package FRM_Elecciones_Ina_Suazo;

/**
 *
 * @author inalaurasuazo
 */
public class java extends javax.swing.JFrame {

    /**
     * Creates new form java
     */
    public java() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Txtelecciones = new javax.swing.JLabel();
        txtcandidatos = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        Btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Txtelecciones.setText("Elecciones Honduras ");
        getContentPane().add(Txtelecciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 20, -1, 28));

        txtcandidatos.setText("Candidatos");
        getContentPane().add(txtcandidatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 54, -1, -1));

        btn1.setText("Votar 1+");
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 171, -1, -1));

        Btn2.setText("Votar+1");
        getContentPane().add(Btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 171, -1, -1));

        btn3.setText("Votar+1");
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 171, -1, -1));

        btn4.setText("Indicar Ganador");
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 237, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(java.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(java.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(java.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(java.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new java().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn2;
    private javax.swing.JLabel Txtelecciones;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JLabel txtcandidatos;
    // End of variables declaration//GEN-END:variables
}
